### ISSUE TITLE
Search query fails on develop.wobbly.app

### ISSUE THREAD

**Issue by chrisdevereux** [Wobbly-App/graphql-backend#99]
![image](https://user-images.githubusercontent.com/361391/54961246-da9d4600-4f57-11e9-9600-2efbd6bdc572.png)

Maybe a migration needs to be run?

If so, maybe we should we add a deploy hook to automatically run migrations so that this kind of thing doesn't happen in future

**Comment by brortao** [comment]
this happened because development environments used the prisma service and stage `default$default`, whereas production uses `wobbly-prisma$dev`. i've now standardized this in #104.
